
GET http://localhost:4000/parcels/
#-----GETS ALL THE parcels FROM THE DATABASE THAT EXIST

######
 POST http://localhost:4000/parcels/
Content-Type: application/json

{
"senderEmail": "evannji99@gmail.com",
"receiverEmail": "briankyalo416@gmail.com",
"SendingLocation": "Nairobi",
"PickupLocation": "Kisumu"
}
