
GET http://localhost:5000/parcels
#-----GETS ALL THE parcels FROM THE DATABASE THAT EXIST

######
GET http://localhost:5000/parcels/sending/ivonnenabangala@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NjQyNGVhOC1mODRlLTRlMDktOTFiZi01Mjc4ZTEyNDdhMDYiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3Mzk3NDc5MzMsImV4cCI6MTczOTc1MTUzM30.Tt7U0wPNrLpwMjcxoBdaZchKabF7jVDgq6hkDhTTyEo
#GETS OUTGOING PARCELS FOR A USER 
#---PARCELS SENT BY A USER

#######

GET http://localhost:5000/parcels/receiving/ivonnenabangala@gmail.com
# GETS INCOMING PARCELS FOR A USER 

######
POST http://localhost:5000/parcels
Content-Type: application/json

{ 
    "senderEmail": "evansgith@gmail.com",
    "receiverEmail": "ivonnenabangala@gmail.com",
    "receiverPhone": "+254751335348",
    "sendingLocation": "Nakuru",
    "pickupLocation": "Nyeri"
    
}

#####
GET http://localhost:5000/parcels/sending

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5NjQyNGVhOC1mODRlLTRlMDktOTFiZi01Mjc4ZTEyNDdhMDYiLCJlbWFpbCI6Iml2b25uZW5hYmFuZ2FsYUBnbWFpbC5jb20iLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3Mzk3NDkzMTEsImV4cCI6MTczOTc1MjkxMX0.GT-jS2LRcbhY3bSH_DoZtIsp9pJT_FHjOdzmzUyVWr8