POST http://localhost:5000/users/registerUser
Content-Type: application/json

{
    "UserName":"Ivonne",
    "Email":"Deleteme@example1.com",
    "Password":"Test@2024"

}

GET http://localhost:5000/users/getAllUsers
#-----GETS ALL THE users FROM THE DATABASE THAT EXIST

######