POST http://localhost:5000/users/registerUser
Content-Type: application/json

{
    "FullName":"Sam",
    "Email":"samwels036@gmail.com",
    "Password":"Test@2024",
    "ProfilePicture": "sbcbjs",
    "Phone": "sncis",
    "Role": "Admin" 

}
####
POST http://localhost:5000/users/login
Content-Type: application/json

{
    
    "Email":"Test1@example1.com",
    "Password":"Test@2024"

}
####
GET http://localhost:5000/users/getAllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkYTJjMDk5Mi1jYTJhLTRlNmItODA0ZS05YTAyMDg3ZWVhNDUiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE3Mzk1Mzg1MjAsImV4cCI6MTczOTU0MjEyMH0.qoSD90VuN5jZRtAzLA3WC9WSG0MIj_M00PJewTl78pY
#-----GETS ALL THE users FROM THE DATABASE THAT EXIST

######

GET http://localhost:5000/users/getUserById/e48b3296-6ca4-4c95-8f47-202c755369fd
# ----GET A USER BY ID


######
GET http://localhost:5000/users/getUserByEmail/Deleteme@example1.com