POST http://localhost:5000/users/registerUser
Content-Type: application/json

{
    "FullName":"Evan",
    "Email":"evannji99@gmail.com",
    "Password":"Test@2024",
    "ProfilePicture": "sbcbjs",
    "Phone": "sncis",
    "Role": "Admin" 

}
####
POST http://localhost:4000/users/login
Content-Type: application/json

{
    
    "Email":"briankyalo27@tshsgs.com",
    "Password":"Kenya"

}
####
GET http://localhost:4000/users/getAllUsers

#-----GETS ALL THE users FROM THE DATABASE THAT EXIST

######

GET http://localhost:5000/users/getUserById/e48b3296-6ca4-4c95-8f47-202c755369fd
# ----GET A USER BY ID


######
GET http://localhost:5000/users/getUserByEmail/Deleteme@example1.com